org: marquespaulov
app: serverless-websocket-api
service: serverless-websocket-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  stage: "dev"
  region: sa-east-1

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:DeleteItem"
            - "dynamodb:Scan"
            - "dynamodb:GetItem"
            - "dynamodb:UpdateItem"
            - "dynamodb:Query"
          Resource:
            - { "Fn::GetAtt": [ "ClientsTable", "Arn" ] }
        - Effect: Allow
          Action:
            - "execute-api:*"
          Resource:
            Fn::Join:
              - ""
              - - "arn:aws:execute-api:"
                - Ref: AWS::Region
                - ":"
                - Ref: AWS::AccountId
                - ":"
                - Ref: WebsocketsApi
                - "/dev/*"

  environment:
    CLIENTS_TABLE_NAME: "WSClientsTable"
    WSS_API_GATEWAY_ENDPOINT:
      Fn::Join:
        - ""
        - - "https://"
          - Ref: WebsocketsApi
          - ".execute-api."
          - Ref: AWS::Region
          - ".amazonaws.com/dev"

functions:
  websocketConnect:
    handler: src/ws-handlers/connect.handler
    events:
      - websocket:
          route: $connect
  websocketDisconnect:
    handler: src/ws-handlers/disconnect.handler
    events:
      - websocket:
          route: $disconnect
  websocketMessage:
    handler: src/ws-handlers/message.handler
    events:
      - websocket:
          route: msg

plugins:
  - serverless-plugin-typescript

resources:
  Resources:
    ClientsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.CLIENTS_TABLE_NAME}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: deviceId
            AttributeType: S
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: deviceId
            KeyType: HASH
          - AttributeName: connectionId
            KeyType: RANGE
        TimeToLiveSpecification:
          AttributeName: expiresAt
          Enabled: true